export const jobs = [
  {
    logo: "/company-logo.png",
    company: "Agrani Printing Press",
    title: "Area Manager (Marketing)",
  },
  {
    logo: "/company-logo.png",
    company: "Delivery Tiger",
    title: "ডেলিভারি রাইডার যাত্রাবাড়ী",
  },
  {
    logo: "/company-logo.png",
    company: "Bdjobs.com Limited",
    title: "Corporate Sales Executive (Male)",
  },
  {
    logo: "/company-logo.png",
    company: "BRAC University",
    title: "Assistant Director (Civic Engagement)",
  },
  {
    logo: "/company-logo.png",
    company: "Agrani Printing Press",
    title: "Area Manager (Marketing)",
  },
  {
    logo: "/company-logo.png",
    company: "Delivery Tiger",
    title: "ডেলিভারি রাইডার যাত্রাবাড়ী",
  },
  {
    logo: "/company-logo.png",
    company: "Bdjobs.com Limited",
    title: "Corporate Sales Executive (Male)",
  },
  {
    logo: "/company-logo.png",
    company: "BRAC University",
    title: "Assistant Director (Civic Engagement)",
  },
  {
    logo: "/company-logo.png",
    company: "Agrani Printing Press",
    title: "Area Manager (Marketing)",
  },
  {
    logo: "/company-logo.png",
    company: "Delivery Tiger",
    title: "ডেলিভারি রাইডার যাত্রাবাড়ী",
  },
  {
    logo: "/company-logo.png",
    company: "Bdjobs.com Limited",
    title: "Corporate Sales Executive (Male)",
  },
  {
    logo: "/company-logo.png",
    company: "BRAC University",
    title: "Assistant Director (Civic Engagement)",
  },
  {
    logo: "/company-logo.png",
    company: "Agrani Printing Press",
    title: "Area Manager (Marketing)",
  },
  {
    logo: "/company-logo.png",
    company: "Delivery Tiger",
    title: "ডেলিভারি রাইডার যাত্রাবাড়ী",
  },
  {
    logo: "/company-logo.png",
    company: "Bdjobs.com Limited",
    title: "Corporate Sales Executive (Male)",
  },
  {
    logo: "/company-logo.png",
    company: "BRAC University",
    title: "Assistant Director (Civic Engagement)",
  },
  {
    logo: "/company-logo.png",
    company: "Agrani Printing Press",
    title: "Area Manager (Marketing)",
  },
  {
    logo: "/company-logo.png",
    company: "Delivery Tiger",
    title: "ডেলিভারি রাইডার যাত্রাবাড়ী",
  },
  {
    logo: "/company-logo.png",
    company: "Bdjobs.com Limited",
    title: "Corporate Sales Executive (Male)",
  },
  {
    logo: "/company-logo.png",
    company: "BRAC University",
    title: "Assistant Director (Civic Engagement)",
  },
  {
    logo: "/company-logo.png",
    company: "Agrani Printing Press",
    title: "Area Manager (Marketing)",
  },
  {
    logo: "/company-logo.png",
    company: "Delivery Tiger",
    title: "ডেলিভারি রাইডার যাত্রাবাড়ী",
  },
  {
    logo: "/company-logo.png",
    company: "Bdjobs.com Limited",
    title: "Corporate Sales Executive (Male)",
  },
  {
    logo: "/company-logo.png",
    company: "BRAC University",
    title: "Assistant Director (Civic Engagement)",
  },
  {
    logo: "/company-logo.png",
    company: "Agrani Printing Press",
    title: "Area Manager (Marketing)",
  },
  {
    logo: "/company-logo.png",
    company: "Delivery Tiger",
    title: "ডেলিভারি রাইডার যাত্রাবাড়ী",
  },
  {
    logo: "/company-logo.png",
    company: "Bdjobs.com Limited",
    title: "Corporate Sales Executive (Male)",
  },
  {
    logo: "/company-logo.png",
    company: "BRAC University",
    title: "Assistant Director (Civic Engagement)",
  },
  {
    logo: "/company-logo.png",
    company: "Agrani Printing Press",
    title: "Area Manager (Marketing)",
  },
  {
    logo: "/company-logo.png",
    company: "Delivery Tiger",
    title: "ডেলিভারি রাইডার যাত্রাবাড়ী",
  },
  {
    logo: "/company-logo.png",
    company: "Bdjobs.com Limited",
    title: "Corporate Sales Executive (Male)",
  },
  {
    logo: "/company-logo.png",
    company: "BRAC University",
    title: "Assistant Director (Civic Engagement)",
  },
  {
    logo: "/company-logo.png",
    company: "Agrani Printing Press",
    title: "Area Manager (Marketing)",
  },
  {
    logo: "/company-logo.png",
    company: "Delivery Tiger",
    title: "ডেলিভারি রাইডার যাত্রাবাড়ী",
  },
  {
    logo: "/company-logo.png",
    company: "Bdjobs.com Limited",
    title: "Corporate Sales Executive (Male)",
  },
  {
    logo: "/company-logo.png",
    company: "BRAC University",
    title: "Assistant Director (Civic Engagement)",
  },
];

export const dummyJobs = [
  {
    id: "1",
    title: "Web Designer/Frontend Developer",
    company: "Datastone",
    companyLogo: "/company-logo.png",
    experience: "0-1 Yrs",
    salary: "Not disclosed",
    location: "Malappuram",
    description:
      "Designing of Website, UI Interface etc... Must have experience in frontend ...",
    skills: [
      "jQuery",
      "Front end",
      "Web technologies",
      "GIMP",
      "html5",
      "Javascript",
      "HR",
    ],
    postedDate: "30+ Days Ago",
    workMode: "Office",
    jobType: "Full-Time",
    companyType: "Startup",
    deadline: "2023-02-20",
  },
  {
    id: "2",
    title: "Front End Web Developer",
    company: "3SA Infosystem",
    companyLogo: "/company-logo.png",
    experience: "0-2 Yrs",
    salary: "Not disclosed",
    location: "Kolkata",
    description:
      "of vacancies: 5. Qualification: Any Graduate. Hands on experience in word...",
    skills: [
      "front end",
      "css",
      "wordpress",
      "ui development",
      "bootstrap",
      "ajax",
      "javascript",
      "jquery",
    ],
    postedDate: "30+ Days Ago",
    workMode: "Remote",
    jobType: "Part-Time",
    companyType: "Corporate",
    deadline: "2023-02-20",
  },
  {
    id: "3",
    title: "React Developer",
    company: "Tech Solutions",
    companyLogo: "/company-logo.png",
    experience: "1-3 Yrs",
    salary: "৳4,00,000 - ৳6,00,000",
    location: "Bangalore",
    description:
      "We are looking for a skilled React Developer to join our development team and help build modern web applications.",
    skills: [
      "React",
      "JavaScript",
      "HTML",
      "CSS",
      "Redux",
      "Webpack",
      "Node.js",
    ],
    postedDate: "15+ Days Ago",
    workMode: "Hybrid",
    jobType: "Full-Time",
    companyType: "IT Services",
    deadline: "2023-02-20",
  },
  {
    id: "4",
    title: "Backend Developer (Node.js)",
    company: "DevWorks",
    companyLogo: "/company-logo.png",
    experience: "2-4 Yrs",
    salary: "৳6,00,000 - ৳9,00,000",
    location: "Hyderabad",
    description:
      "Join our dynamic team of backend engineers to build scalable and robust backend systems using Node.js and MongoDB.",
    skills: ["Node.js", "MongoDB", "Express", "API Design", "REST", "GraphQL"],
    postedDate: "10+ Days Ago",
    workMode: "Remote",
    jobType: "Full-Time",
    companyType: "Startup",
    deadline: "2023-02-20",
  },
  {
    id: "5",
    title: "Mobile App Developer (React Native)",
    company: "App Innovators",
    companyLogo: "/company-logo.png",
    experience: "1-3 Yrs",
    salary: "৳3,00,000 - ৳5,00,000",
    location: "Mumbai",
    description:
      "Develop cross-platform mobile applications with React Native. Work on exciting mobile app projects.",
    skills: [
      "React Native",
      "JavaScript",
      "Redux",
      "React",
      "Mobile Development",
    ],
    postedDate: "5+ Days Ago",
    workMode: "Remote",
    jobType: "Contract",
    companyType: "Tech Startup",
    deadline: "2023-02-20",
  },
  {
    id: "6",
    title: "UI/UX Designer",
    company: "Designify",
    companyLogo: "/company-logo.png",
    experience: "1-2 Yrs",
    salary: "৳2,50,000 - ৳4,00,000",
    location: "Pune",
    description:
      "Responsible for designing user interfaces and enhancing user experiences across digital platforms.",
    skills: [
      "UI Design",
      "UX Design",
      "Adobe XD",
      "Figma",
      "Sketch",
      "Wireframing",
    ],
    postedDate: "25+ Days Ago",
    workMode: "Office",
    jobType: "Full-Time",
    companyType: "Design Agency",
    deadline: "2023-02-20",
  },
  {
    id: "7",
    title: "Software Engineer",
    company: "CodeCrafters",
    companyLogo: "/company-logo.png",
    experience: "3-5 Yrs",
    salary: "৳7,00,000 - ৳10,00,000",
    location: "Chennai",
    description:
      "Looking for a passionate software engineer to work on high-scale enterprise software solutions.",
    skills: ["Java", "Spring Boot", "SQL", "Microservices", "AWS"],
    postedDate: "1+ Week Ago",
    workMode: "Hybrid",
    jobType: "Full-Time",
    companyType: "Enterprise",
    deadline: "2023-02-20",
  },
  {
    id: "8",
    title: "Graphic Designer",
    company: "Creative Hub",
    companyLogo: "/company-logo.png",
    experience: "0-2 Yrs",
    salary: "৳2,00,000 - ৳3,50,000",
    location: "Delhi",
    description:
      "Design and create visually appealing graphics for digital and print media. Freshers with strong portfolios are welcome.",
    skills: [
      "Photoshop",
      "Illustrator",
      "Design Principles",
      "Branding",
      "Typography",
    ],
    postedDate: "20+ Days Ago",
    workMode: "Office",
    jobType: "Part-Time",
    companyType: "Design Agency",
    deadline: "2023-02-20",
  },
  {
    id: "9",
    title: "Full Stack Developer",
    company: "Techie Solutions",
    companyLogo: "/company-logo.png",
    experience: "3-5 Yrs",
    salary: "৳8,00,000 - ৳12,00,000",
    location: "Bangalore",
    description:
      "Seeking a Full Stack Developer with expertise in both frontend and backend technologies to build complex applications.",
    skills: ["React", "Node.js", "Express", "MongoDB", "GraphQL", "AWS"],
    postedDate: "12+ Days Ago",
    workMode: "Hybrid",
    jobType: "Full-Time",
    companyType: "IT Services",
    deadline: "2023-02-20",
  },
  {
    id: "10",
    title: "Digital Marketing Specialist",
    company: "MarketPro",
    companyLogo: "/company-logo.png",
    experience: "2-4 Yrs",
    salary: "৳4,50,000 - ৳6,50,000",
    location: "Gurgaon",
    description:
      "Manage digital marketing campaigns, including SEO, SEM, email marketing, and social media.",
    skills: [
      "SEO",
      "Google Ads",
      "Social Media",
      "Analytics",
      "Content Marketing",
    ],
    postedDate: "7+ Days Ago",
    workMode: "Remote",
    jobType: "Full-Time",
    companyType: "Marketing Agency",
    deadline: "2023-02-20",
  },
];

// use appliedjobs and application page
export const applications = [
  {
    company: "Systemic Altruism",
    profile: "Full Stack Startup Founder Job",
    appliedOn: "28 Nov' 24",
    applicants: 87,
    status: "Applied",
  },
  {
    company: "Episodiclabs Private Limited (Tecnikilab)",
    profile: "Web Development Internship",
    appliedOn: "28 Nov' 24",
    applicants: 3,
    status: "Applied",
  },
  {
    company: "Persist Ventures",
    profile: "Front End Developer Job",
    appliedOn: "28 Nov' 24",
    applicants: 5197,
    status: "Applied",
  },
];
